### ISSUE TITLE
URLs are being incorrectly normalized

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#114]
Some URLs in ours adoc files are being incorrectly normalized.

For example, see the URL specified in [this adoc file](https://github.com/hlxsites/prisma-cloud-docs/blob/main/docs/en/compute/30-xx/admin-guide/configure/permissions.adoc?plain=1#L14):

```
[format=csv, options="header"]
|===
include::https://docs.google.com/spreadsheets/d/e/2PACX-1vQGxhsOAAuj13OSYtAJCzU2CQ5G12FZxro0vHaqf8Tzcm96ZCxhxAW2jeT3__HfvliAMXUwGG_Hly8g/pub?output=csv&gid=338970097[]
|===
```

When you examine how the Franklin worker transforms the page (see [here](https://main--prisma-cloud-docs--hlxsites.hlx.page/prisma/prisma-cloud/docs/en/compute/30-xx/admin-guide/configure/permissions)), you'll see the URL has been improperly normalized:

```
https://docs.google.com/spreadsheets/d/e/2PACX-1vQGxhsOAAuj13OSYtAJCzU2CQ5G12FZxro0vHaqf8Tzcm96ZCxhxAW2jeT3__HfvliAMXUwGG_Hly8g/pub?output=csv&gid=338970097
```

Some things that are wrong with the normalization:

* URL path parts are lower-cased. [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986) says "the scheme and host are case-insensitive and therefore should be normalized to lowercase. For example, the URI <HTTP://www.EXAMPLE.com/> is equivalent to <http://www.example.com/>. _The other generic syntax components are assumed to be case-sensitive unless specifically defined otherwise by the scheme_"
* Underscores are replaced with dashes
* Multiple underscores are replaced with a single dash.

**Comment by iansk** [comment]
For convenience, here's a side-by-side comparison of the two URLs:

```
# [Input] URL from the adoc file:
https://docs.google.com/spreadsheets/d/e/2PACX-1vQGxhsOAAuj13OSYtAJCzU2CQ5G12FZxro0vHaqf8Tzcm96ZCxhxAW2jeT3__HfvliAMXUwGG_Hly8g/pub?output=csv&gid=338970097

# [Output] URL transformed by worker:
https://docs.google.com/spreadsheets/d/e/2pacx-1vqgxhsoaauj13osytajczu2cq5g12fzxro0vhaqf8tzcm96zcxhxaw2jet3-hfvliamxuwgg-hly8g/pub?output=csv&gid=338970097
```

**Comment by icaraps** [comment]
Fixed with https://github.com/hlxsites/prisma-cloud-docs/commit/f5b15001b6d3b22c480fd37621f3b42073094004
