### ISSUE TITLE
Load issue 2

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#116]
I'm still seeing the load issue. I can reproduce the issue most times, but not consistently every time.

**Repro:**

1. Go to this page:

   https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/30-xx/admin-guide?branch=ian-gsheet

2. In the ToC, expand "Adminstrator's Guide", then expand "Configure".

3. In the ToC, scroll to the last entry in the "Configure" section, and click on "Permissions".

   <img width="342" alt="load-issue2-toc-click-permissions" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/deb2afbf-f17f-48a8-a10f-e78b08331115">

4. Notice that the page doesn't load.

**Results:**

Neither the ToC nor the adoc content load.

<img width="1463" alt="load-issue2-blank-page" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/8553163a-2a81-431e-b540-c9f185d3d42d">

**Expected results:**

Page fully loads

**Debug info:**

After loading the first page in step 1, this is what I saw in the Developer Tools console:

<img width="1503" alt="load-issue2-first-page-console" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/d6ced790-43ff-485a-992a-30d1e60c0609">

After loading the "Permissisons" page, this is what I saw in the Developer Tools console:

<img width="1506" alt="load-issue2-second-page-console" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/968744b1-0351-4ace-b436-71df7fd77a94">

**Comment by icaraps** [comment]
I was able to reproduce it after a couple of times. Looking into it ...
