### ISSUE TITLE
Page with adoc/gdoc content not loading

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#124]
I've reproduced a case where a page fails to load.

1. Open a fresh incognito window in Chrome.

2. Go to this [preview link](https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/cspm/use-cases/risk-prevention/use-case2?branch=ian-use-cases).

3.  The page may or not load. It loads for me.

4. In the ToC, click "Use Case 1"

   <img width="1466" alt="click-use-case1" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/784668c6-65c6-4343-b5b7-989abdb4affd">

5. The page doesn't fully load. Both the nav and the adoc/gdoc content are missing.

   <img width="1466" alt="page-does-not-load" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/d5d27efb-9b23-4897-a32f-5e3ba7568121">

**Additional info**

In the dev tools, there are no errors in the Console. I captured the following network events:

Page 1:

<img width="1497" alt="dev-tools-page1" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/5f5a14fb-5d2e-405a-bb66-5dc6da99fb00">

Page 2:

<img width="1497" alt="dev-tools-page2" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/a39ddd53-c666-4304-b31d-d49cc0cac586">

**Comment by maxakuru** [comment]
put a possible fix in with https://github.com/hlxsites/prisma-cloud-docs-website/commit/15a90940f66881964b23ded16f6a529bd0c63e49 - please give it a try

**Comment by iansk** [comment]
Thanks @maxakuru. This is working now.
