### ISSUE TITLE
Books are broken on local

### ISSUE THREAD

**Issue by charlieboles** [hlxsites/prisma-cloud-docs-website#126]
**Observation of the Issue/Behavior**
When attempting to develop on local (main branch) books do not load. 

**Expected Result/Behavior**
Books should load without issue on local (main branch)

**Steps to Reproduce**

1. Pull the latest commit [https://github.com/hlxsites/prisma-cloud-docs-website/commit/15a90940f66881964b23ded16f6a529bd0c63e49](commit)
2. Run in dev mode `npm run dev`
3. Navigate to [http://localhost:3000/prisma/prisma-cloud/en/compute/pcee/admin-guide/install/install-windows](http://localhost:3000/prisma/prisma-cloud/en/compute/pcee/admin-guide/install/install-windows) in your browser.
4. Notice that the book does not load and the errors in the console.

Devices Used
macOS 13.4.1

Browsers Used
Chrome 115.0.5790.102

<img width="844" alt="Screenshot 2023-07-25 at 11 14 14 AM" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/2379680/866609f7-781f-483c-b3e6-e98b377c0b21">
<img width="1445" alt="Screenshot 2023-07-25 at 11 14 38 AM" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/2379680/fac39923-8e81-4dd0-a823-7403503de54c">

**Comment by maxakuru** [comment]
@charlieboles I can't reproduce this, just to confirm and leave a trail in the issue:
1. did you pull both repos? [docs](https://github.com/hlxsites/prisma-cloud-docs) and [website](https://github.com/hlxsites/prisma-cloud-docs-website)
2. did you install dependencies in both? `npm i`
3. are you running both in dev mode? `npm run dev`

**Comment by charlieboles** [comment]
@maxakuru Thank you for looking into this. Yes, all 3 steps were followed. I went ahead and did a full system restart and that fixed the issue.
