### ISSUE TITLE
[AsciiDoctor conversion] tt inline macro

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#138]
We need to port a custom [AsciiDoctor extension](https://docs.asciidoctor.org/asciidoctor/latest/extensions/) forward to Franklin.

We have a number of AsciiDoctor extensions. We can deprecate all of them except one [inline macro](https://docs.asciidoctor.org/asciidoctor/latest/extensions/inline-macro-processor/) that has the following syntax:

```
tt:[text]
```

The input `text` is typically some sort of one or two word "label", that's styled as a pill with white text and a black background. For example:

```
tt:[Update]
```

Output:

<img width="68" alt="franklin-uat-tt-macro-output" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/48b585c5-9557-48f9-96d8-03d06a70251a">

**Example AsciiDoc input:**

https://github.com/hlxsites/prisma-cloud-docs/blob/a0d4175a6e85dd7e362e141413520aeb34fe3938/docs/en/cspm/rn/prisma-cloud-release-information/features-introduced-in-2023/features-introduced-in-march-2023.adoc?plain=1#L48

```
|tt:[Update] *AWS Config*
```

**Current Franklin output:**

https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/cspm/rn/prisma-cloud-release-information/features-introduced-in-2023/features-introduced-in-march-2023

<img width="1472" alt="franklin-uat-tt-macro-current-franklin-output" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/76be059d-9289-4f36-b01d-d211e3d09549">

**Desired output:**

Here's the equivalent page on our current doc site:

https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-release-notes/prisma-cloud-release-information/features-introduced-in-2023/features-introduced-in-march-2023

<img width="1471" alt="franklin-uat-tt-macro-current-aem-output" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/50524b06-84d4-43f8-a681-c9f45cfed1e8">

**Comment by maxakuru** [comment]
#141 implements this client-side, imo that's a better option than a custom conversion rule for a relatively small text style
