### ISSUE TITLE
[AsciiDoc conversion] Image scaling

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#139]
Setting the `width` and `height` attributes in the AsciiDoctor source has no effect on the size of the image in the HTML output.

**AsciiDoctor input:**

https://github.com/hlxsites/prisma-cloud-docs/blob/7102ef810abaa445ed92c9c36a017701e356f856/docs/en/compute/pcee/admin-guide/welcome/test-asciidoc.adoc?plain=1#L64-L91

Relevant code:

```
Test1 - Normal size

image::test1.png[]

Test2 - Scale by width

image::test1.png[width=100]

Test3 - Scale by height

image::test1.png[height=100]
```

**Franklin output:**

https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/welcome/test-asciidoc?branch=ian/test-asciidoc

Scroll down to the section "Image sizing". Notice that all images are the same size. The second and third images should be scaled down in size.

**Reference info:**

* https://docs.asciidoctor.org/asciidoc/latest/macros/image-size/

**Comment by maxakuru** [comment]
there are 2 parts to this:
1. setting the values in the conversion, this already worked but I added the default unit of `%` when one doesn't exist
2. setting the img width/height in CSS on the client

for 2, this PR will remove the automatic scaling to 100% of possible width: https://github.com/hlxsites/prisma-cloud-docs-website/pull/140

@iansk I'll leave it up to you to decide whether that's something that applies everywhere, the implication being that the images may not fill the entire width of a section/page, and authors should explicitly define them

**Comment by maxakuru** [comment]
if this is still an issue please reopen with an example
