### ISSUE TITLE
Book not loading in sidenav

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#158]
One book's ToC doesn't load in the left nav.

Repro:

1. Go to this link: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/enterprise-edition/use-cases/visibility-control/visibility-control

2. Notice that the nav for the `Prisma Cloud Application Security Policy Reference` doesn't work.

<img width="364" alt="left-nav-policy-ref" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/e6408536-348f-475f-8ae7-d520b3cc1e9d">

3. Open the Dev Tools. In the Console, there are these errors. The last one pops up after mousing over the `Prisma Cloud Application Security Policy Reference` book in the sidenav.

<img width="1472" alt="left-nav-policy-ref-console-errors" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/e0364163-7ae8-4a0b-80c5-d476557ebd19">

**NOTE:** The `Prisma Cloud Application Security Policy Reference` properly loads in the sidenav in the Franklin dev environment (i.e. I can't reproduce the issue there). What's the difference between the prod environment and the dev env?

**Comment by iansk** [comment]
@maxakuru I still see the exact same issue. Tested in an incognito window just a moment ago.

The left nav doesn't work for the "Policy Reference" book, and I see the same JavaScript error in the Dev Tools console.

**Comment by maxakuru** [comment]
should be fixed in #160

**Comment by iansk** [comment]
Looks good, thanks
