### ISSUE TITLE
product landing pages

### ISSUE THREAD

**Issue by maxakuru** [hlxsites/prisma-cloud-docs-website#16]
landing page for each product:
`/prisma/prisma-cloud/en/cns`
`/prisma/prisma-cloud/en/code-security`
`/prisma/prisma-cloud/en/compute`
`/prisma/prisma-cloud/en/cspm`

- similar to ref page, except not including the individual version pickers
- sidenav should be excluded on these pages
- page will be identical across each product to start, content can be adjusted as it's available
- only `en` locale to start

doc: https://docs.google.com/document/d/1tjRD0tNm4C0hmqV-IefQeh2U1PZSTArI3KY_mfzjKuY/edit#heading=h.sjklulsvah0w
ref: https://docs.paloaltonetworks.com/prisma/prisma-cloud

**Comment by iansk** [comment]
We'd like a three-level hierarchy:

1. Top/first page: Division landing page (prisma/prisma-cloud). This has links to specific products.

2. Second level: Product landing page:

- There will be several product landing pages: "Compute", "CSPM", "CNS", "Code Security".
- These pages will all look lijke this [page](https://docs.paloaltonetworks.com/prisma/prisma-cloud) MINUS the "Documentation" section, which, in the current site, lists all books. We don't need that anymore. We just need a link that says something like "Go to the docs", which takes you the third level.
- At the bottom of the page, we should still have the "Related Videos & Blogs" section

3. Third level: The doc page(s) for the product, with the multi-book nav, and articles loaded from the prisma-cloud-docs site.

All these details are specified [here](https://docs.google.com/document/d/1ZUHVeKw_E7q6n83ST9ws28fJDFY2ZnangB9gHxpBUuA/edit#heading=h.qaonxmfhdtma) under the section "Site hierarchy".

**Comment by maxakuru** [comment]
mixed the division & product landing pages up, corrected with #25
