### ISSUE TITLE
[AsciiDoc conversion] Cross reference link text

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#168]
For cross-doc references, you must specify the link text. For example:

```
xref:another-topic.adoc[Another topic]
```

The link text is specified between the two square brackets. The current AsciiDoc converter isn't processing this directive. Instead, the link text appears as `undefined`.

<img width="1469" alt="franklin-uat-xref-link-text" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/e2d0ce26-9c5b-4aa4-b8e9-c14eeb3077b1">

**Repro:**

1. See a live page here: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/enterprise-edition/content-collections/get-started/get-going#first-steps

2. See the corresponding AsciiDoc source here: https://github.com/hlxsites/prisma-cloud-docs/blob/664c01f293f4abae1fdc6b87297aff43571fbad3/docs/en/enterprise-edition/content-collections/get-started/get-going.adoc?plain=1#L13-L17

**Comment by maxakuru** [comment]
@iansk this is fixed, for example: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/enterprise-edition/content-collections/get-started/get-going

I just noticed this page has a broken image though, it looks like it's because it's a `.gif` that's too large (28mb)
