### ISSUE TITLE
[sitemap-index] sitemap not accessible

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#190]
Our Coveo index operation is failing based on the current contents of `sitemap-index`.

```
<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <sitemap>
    <loc>https://main--prisma-cloud-docs--hlxsites.hlx.live/docs/sitemaps/sitemap-en-0.xml</loc>
  </sitemap>
  <sitemap>
    <loc>https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/sitemap.xml</loc>
  </sitemap>
</sitemapindex>
```

`sitemap-index` contains this entry: `https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/sitemap.xml`, but Coveo can't access it. I tried plugging the URL in my browser, but I get a 404.

**Comment by maxakuru** [comment]
this is fixed now, the query-index spreadsheets needed the `helix-default` sheet to be created and to be preview/published.. 

also added a cron job to publish english sitemaps every day at 5pm here: https://docs.google.com/spreadsheets/d/1mTdKBLqEytaGJ3o29V_wKyV_iG52i-HrvkvR0JyrbIs/edit#gid=0
