### ISSUE TITLE
[Pre-prod site] Images not loading

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#193]
Images that load/render on our dev site aren't loading/rendering on our pre-prod site (docs-preview.prismacloud.io). For example:

Dev site:
https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/enterprise-edition/content-collections/governance/attack-path-policies

Pre-prod site:
https://docs-preview.prismacloud.io/en/enterprise-edition/content-collections/governance/attack-path-policies

**Screenshots:**

Dev site:

<img width="1473" alt="franklin-images-dev-site" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/fdca4a70-90f3-4552-a6fc-15e73e0dbe41">

Pre-prod site:

<img width="1471" alt="franklin-images-pre-prod-site" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/32b7e74b-2ec0-4413-b0a5-e9c196ae8520">

**Comment by maxakuru** [comment]
fixed in #196 and #197
