### ISSUE TITLE
Preview/live not aligned

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#195]
From Slack

I just pushed an article (adoc) live using the REST API:

**Preview:**

```
curl -vi -XPOST 'https://admin.hlx.page/preview/hlxsites/prisma-cloud-docs/main/docs/en/enterprise-edition/rn/known-issues/known-issues'
```

**Live:**

```
curl -vi -XPOST 'https://admin.hlx.page/live/hlxsites/prisma-cloud-docs/main/docs/en/enterprise-edition/rn/known-issues/known-issues'
```

On the preview site, I see the fix Max made to address link text that said "undefined" ([GH#168](https://github.com/hlxsites/prisma-cloud-docs-website/issues/168)):

https://main--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/rn/known-issues/known-issues

But on the live site, I don't see the fix.

https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/enterprise-edition/rn/known-issues/known-issues
I opened both pages in fresh new incognito windows.

Questions:
* Is there a delay between hitting the publish REST endpoint, and the actual content going live?
* How long should I expect to wait to see the new content?
* Technically, what's going on under the covers?

**Comment by maxakuru** [comment]
answered questions on Slack, looks like this was a race condition on preview/publish
