### ISSUE TITLE
[AsciiDoc conversion] Inline cross references in table cells wrapped in para tags

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#201]
Inline cross references (with the AsciiDoc `xref:` macro) are being wrapped in an extra `<p>` tag when the cross reference is in a table cell.

For example, this [AsciiDoc source](https://github.com/hlxsites/prisma-cloud-docs/blob/d9aa561415a82cd7d0ed30f5c70c5c8457d76f21/docs/en/enterprise-edition/content-collections/application-security/familiarize-application-security.adoc?plain=1#L72) specifies that everything, including the cross-ref, should be in a single para:

```
A comprehensive view of an organization's engineering technical stack from repository to deployment. See xref:visibility/repositories.adoc[here] for more on Repositories.
```

But the link in the table is put into it's own para. Screenshot of this issue (the first red box corresponds to the AsciiDoc code snippet above):

<img width="821" alt="franklin-uat-xrefs-in-tables" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/a1f2239b-dafc-4388-864c-4eab28167b93">

Link to the page:

https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/enterprise-edition/content-collections/application-security/familiarize-application-security#fundamental-concepts

When inspecting the link element, I see it's wrapped in an extra `<p>` tag:

<img width="803" alt="franklin-uat-xrefs-in-tables2" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/3ad2f8ca-2697-4ccc-adeb-101a9f34fdad">

**Expected result:**

There should be no extra `<p>` tag around cross references, unless explicitly specified in the underlying AsciiDoc source. In the screenshot, all the text in column 2 of both rows should be in a single para, not spread across three paras.

**Comment by maxakuru** [comment]
fixed in https://github.com/hlxsites/prisma-cloud-docs/pull/121 & https://github.com/hlxsites/prisma-cloud-docs/pull/122
will need to republish docs to get those changes
