### ISSUE TITLE
[Sidekick] Cannot preview/publish non Google doc types

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#202]
Using Sidekick, we tried previewing and publishing json, txt, and csv files in our Google Drive folder. We want to be able to link to these files from pages in our doc site so customers can download them.

Here are screenshots of the errors that Sidekick returns:

**JSON file:**

<img width="1473" alt="franklin-uat-pub-json-file" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/3c194644-a856-4aab-b0b2-015d30d12cf8">

**TXT file:**

<img width="1471" alt="franklin-uat-pub-txt-file" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/351ca02c-3ccd-480e-be18-193a578866ef">

**CSV file:**

<img width="1470" alt="franklin-uat-pub-csv-file" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/d112d96b-44c4-47cd-881b-da4a58bcbee8">

**Comment by Pubs-MV** [comment]
What other content formats are supported? 

Also from the assets folder:
- how do I know what is published and live?
- how do I unpublish?
- do you have suggestions on how to manage/track when something was published and unpublished? 
   Today we see this on the AEM DAM and know whether the content is live/published or deactivated or not uyet published and who was the last person who took an action.

**Comment by maxakuru** [comment]
@iansk Those file types can't be authored in Google Drive, but they can be uploaded to Github and managed with code. Code files will be live when committed and pushed to the `main` branch.

as for the questions below, @Pubs-MV:
1. sitemap entries, and for specific docs you can use the [GET /status Admin API](https://www.hlx.live/docs/admin.html#tag/status) for more details
2. if a document is published and you delete/rename it, you'll have the option to unpublish from the sidekick. You can see an example on this page if you open the sidekick: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/drafts/maxed/i-deleted-this-document. Also possible via [DEL /live Admin API](https://www.hlx.live/docs/admin.html#tag/publish/operation/unpublishResource)
3. I think any suggestions would depend on the goals/use-case.. maybe you can bring this to the Slack channel and we can chat there

note those are general answers, not for the file types mentioned in this issue that aren't supported in gdrive

**Comment by iansk** [comment]
@maxakuru We'll store flat text files (json, txt, csv, etc) in the repo for now, as you suggested.

We'll come back and revisit what options we've got post-launch.
