### ISSUE TITLE
[AsciiDoc conversion] Table not rendered correctly

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#207]
The following table has two issues:
* Images in the table aren't being rendered - they're being displayed as gray boxes
* The row span directive (in the AsciiDoc source) isn't being observed in the final HTML table.

<img width="950" alt="franklin-uat-table-row-span-images" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/1b34695b-abe6-4ec7-b2fc-dc7d67df0a79">

**Franklin page:** https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrations-feature-support

**Underyling AsciiDoc source:** https://github.com/hlxsites/prisma-cloud-docs/blob/af5e6b7b9e98c1ada9b7a1e20a67d670f71cc97e/docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrations-feature-support.adoc?plain=1#L7-L210

Note that the line that specifies the row span is [here](https://github.com/hlxsites/prisma-cloud-docs/blob/af5e6b7b9e98c1ada9b7a1e20a67d670f71cc97e/docs/en/enterprise-edition/content-collections/administration/configure-external-integrations-on-prisma-cloud/integrations-feature-support.adoc?plain=1#L26):

```
.19+|xref:../manage-prisma-cloud-alerts/alert-notifications-state-changes.adoc#idb247adc1-9c3f-4e77-8aff-fca99428ce79[Alert Notifications on State Change]
```

**Original doc page where it's being rendered correctly:** https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin/configure-external-integrations-on-prisma-cloud/integrations-feature-support

**Comment by 3vil3mpir3** [comment]
@maxakuru looks like the container for these images has a heightxwidth of 0px
