### ISSUE TITLE
[Versions] RN version not loading

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#210]
Version 22.12 of the RN book doesn't load.

**Repro:**

1. Go to https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/compute-edition/31/rn/get-help/related-documentation

   The page loads

2. In the URL, change `31` to `30`: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/compute-edition/30/rn/get-help/related-documentation

   The page loads

3. In the URL, change `30` to `22-12`: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/compute-edition/22-12/rn/get-help/related-documentation

   The page **doesn't** load.

**Comment by maxakuru** [comment]
caused by a typo in metadata sheet 🥲 

<img width="437" alt="Screenshot 2023-10-16 at 12 41 42 PM" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/17409558/eab1ff58-1e8b-4c67-8129-1f27b7efe412">

**Comment by iansk** [comment]
Arghhhhhhhhhh! Thanks for debugging! :)
