### ISSUE TITLE
[Versions] AG version not loading

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#211]
Version 31 of the AG book doesn't load.

**Repro:**

1. Go to https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/compute-edition/22-12/admin-guide/welcome/welcome

   The page loads.

2. In the URL, change `22-12` to `30`: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/compute-edition/30/rn/get-help/related-documentation

   The page loads.

3. In the URL, change `30` to `31`: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/en/compute-edition/31/rn/get-help/related-documentation

   The page **doesn't** load.

**Comment by maxakuru** [comment]
looks fixed now, closing
