### ISSUE TITLE
Spreadsheet ingestion - specifying sheets not supported

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#215]
When embedding a sheet in a table in an adoc file, you can't specify a sheet.

```
[format=csv, options="header"]
|===
https://main\--prisma-cloud-docs-website\--hlxsites.hlx.live/en/enterprise-edition/assets/apis-ingested-by-prisma-cloud?sheet=oci
|===
```

For example, see this page on the `ian-fix-sheets` branch:

https://main--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-oci-account/oci-apis-ingested-by-prisma-cloud?branch=ian-fix-sheets

Here's the page:

https://main--prisma-cloud-docs-website--hlxsites.hlx.page/en/enterprise-edition/content-collections/connect/connect-cloud-accounts/onboard-your-oci-account/oci-apis-ingested-by-prisma-cloud?branch=ian-fix-sheets

I think it's due to this code in `blocks/table/table.js` in the function `sheetToDivTable`, which doesn't extract and pass the `sheet` param to `fetchJSON`.

**Comment by maxakuru** [comment]
@iansk could you add the .json extension?

```
[format=csv, options="header"]
|===
https://main\--prisma-cloud-docs-website\--hlxsites.hlx.live/en/enterprise-edition/assets/apis-ingested-by-prisma-cloud.json?sheet=oci
|===
```
