### ISSUE TITLE
[Preview] Branch param not working

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#220]
This is weird. Branch previews don't seem to work anymore.

Page content doesn't load with the branch param: 

https://main--prisma-cloud-docs-website--hlxsites.hlx.page/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-aws/onboard-aws-account?branch=ian-test-inline-img

Page content loads properly without the param:

https://main--prisma-cloud-docs-website--hlxsites.hlx.page/en/classic/cspm-admin-guide/connect-your-cloud-platform-to-prisma-cloud/onboard-aws/onboard-aws-account

**Comment by maxakuru** [comment]
fixed in https://github.com/hlxsites/prisma-cloud-docs-website/commit/8c2d5993f9dac18c56ed101123ee278523d6b333
