### ISSUE TITLE
Font icons layout shift 

### ISSUE THREAD

**Issue by icaraps** [hlxsites/prisma-cloud-docs-website#33]
Some icons are loaded via fonts and since the font loading is lazy loaded, a minor layout shift is perceived for all icons loaded this way. For example on an article page https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/pcee/admin-guide/configure/proxy, the next and previous buttons have arrow like icons. 

Ideally we could replace some icons with SVG icons for a better user experience.

**Comment by iansk** [comment]
New design in main now. I don;t think this is relevant anymore.
