### ISSUE TITLE
Google Sheet and Google Doc content

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#37]
We've got some articles that pull data directly from a Google Sheet. It's currently not working in the Franklin site.

See this example:

- [ADOC source file](https://raw.githubusercontent.com/hlxsites/prisma-cloud-docs/main/docs/en/compute/30-xx/admin-guide/configure/permissions.adoc)
- [AEM site](https://docs.paloaltonetworks.com/prisma/prisma-cloud/30/prisma-cloud-compute-edition-admin/configure/permissions)
- [Franklin site](https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/pcee/admin-guide/configure/permissions)

We want to be able to publish both Google Sheet and Google Doc content directly in our docs. This is an important use case for us. We use Google Sheets and Docs to collaborate across technical teams at Palo. For example, sometimes product managers maintain big spreadsheets that contain complex data, that are continuously updated, and that contain info that customers need to know about. By plugging directly into the spreadsheet, we don't have to transcribe the content from one place (i.e. the Google Sheet) to another place (i.e. our docs in adoc format).

**Comment by maxakuru** [comment]
do you have an example of google docs being embed from the existing adoc content? 

would it be enough to make a sample adoc that shows how you can embed a gsheet as a table, then leave the content updates up to you/team? it would be similar to this doc: https://github.com/hlxsites/prisma-cloud-docs/blob/main/docs/examples/gdoc-fragment.adoc

embedding gdoc content would be done just like that example above - gsheet content in a table isn't done yet, but will require moving the content inside the Franklin gdrive root folder and publishing the sheet, then updating the adoc content to point to the published page

**Comment by iansk** [comment]
> do you have an example of google docs being embed from the existing adoc content?

No, I don't have an example of a Google Doc embedded from an existing adoc file, but it's a use case we'd like to support.

The first two links above show a Google Sheet embedded into an existing adoc file.

> would it be enough to make a sample adoc that shows how you can embed a gsheet as a table, then leave the content updates up to you/team? it would be similar to this doc: https://github.com/hlxsites/prisma-cloud-docs/blob/main/docs/examples/gdoc-fragment.adoc

Yes, that would work.

> embedding gdoc content would be done just like that example above - gsheet content in a table isn't done yet, but will require moving the content inside the Franklin gdrive root folder and publishing the sheet, then updating the adoc content to point to the published page

What do you mean by "publish" the sheet? That just means clicking "Publish" from the Franklin sidekick, right?

**Comment by maxakuru** [comment]
> What do you mean by "publish" the sheet? That just means clicking "Publish" from the Franklin sidekick, right?

correct, examples are in #48
