### ISSUE TITLE
Left nav - fixed width

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#39]
The left nav dynamically expands and collapses depending on the width of the entries. It's a jarring experience for readers. The left nav should be fixed width.

Screen cap that shows the issue is attached.

https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/f854f74e-56ed-40f6-90b1-d939f24018b5

**Comment by maxakuru** [comment]
@iansk link to the page in your clip? seems to only happen on pages without doc content in the main area, I think

**Comment by iansk** [comment]
@maxakuru Navigate to this [page](https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/pcee/admin-guide/install), and then expand/collapse the "Install" section.
