### ISSUE TITLE
Changes to adoc file not showing up on the live site

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#52]
When making a change to an adoc file from a branch, and then merging the branch into `main`, the updates to the file can't be seen on the `.live` site.

**Steps**

1. Go to the prisma-cloud-docs repo.
2. Create a new branch (e.g. [ian-test-doc-change](https://github.com/hlxsites/prisma-cloud-docs/tree/ian-test-doc-change))
3. Create a pull request from the branch (e.g. [PR#23](https://github.com/hlxsites/prisma-cloud-docs/pull/23))
4. Merge the PR into `main`.
5. Go to the live site to see the changes (link: [live site](https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/ops-guide/phases/learn))

Note, I'm just making this very simple one line change:

<img width="1436" alt="adoc-file-simple-change" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/2e75479f-8189-4f8c-a534-b49cc74e5d1d">

**Results**

The old version of the file is still being shown.

i.e. The file from commit ID `473c4fd` from May 4, 2023

<img width="1277" alt="adoc-file-commit-history1" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/c9c9bd90-b840-481d-951c-afa0b4bf31b8">

https://github.com/hlxsites/prisma-cloud-docs/commits/main/docs/en/compute/ops-guide/phases/learn.adoc

**Expected results**

The latest version of the file is shown, with changes.

i.e. The file with commit ID `0a2e0f6` from Jun 14, 2023.

<img width="1277" alt="adoc-file-commit-history2" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/314718ab-4c5f-422e-a390-e9028cff44c0">

https://github.com/hlxsites/prisma-cloud-docs/commits/main/docs/en/compute/ops-guide/phases/learn.adoc

**Comment by maxakuru** [comment]
done in https://github.com/hlxsites/prisma-cloud-docs/pull/27
