### ISSUE TITLE
Previewing branches with changes to multiple files

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#53]
While the `branch` query param is great when previewing PRs that change just a single file, we often create PRs that change multiple files. Writers, managers, reviewers, collaborators, and repo maintainers need to be able to seamlessly click through the preview site and see all the changes. Currently, every time you click a link or select an item from the left nav, the `branch` query param is stripped, and you need to manually add it back to the URL. This can become tedious.

This is a common enough use case that we'd like to fix it/find a good solution.

#### Related test case

Previewing a newly added file.

1. Add a new file to the repo.
2. Add it to book.yml.
3. Commit your changes, push to GitHub. (example branch: [ian-add-file](https://github.com/hlxsites/prisma-cloud-docs/tree/ian-add-file))
4. Preview the site, but go to a file that already exists in the repo ([link](https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/ops-guide/phases/learn?branch=ian-add-file)).

   **Result**: If you expand the "Phases" section, you can see the new topic "Test" in the left nav

   <img width="340" alt="add-new-file-left-nav" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/eb815f64-1bcf-4f2b-ad4f-3b339b4636d8">

5. Click the new topic in the left nav.

   **Result**: You get redirected to this URL (https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/not-applicable/ops-guide/getting-started/getting-started), and only the page chrome loads

   <img width="1464" alt="add-new-file-empty-page" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/580128e4-d9b2-41b4-8d5a-4c4277cf860c">

**Comment by iansk** [comment]
@icaraps @maxakuru Just some perspective: getting this right is critical to the success of this project. Quick, full-fidelity previews with minimal fuss is a primary motivator for ditching our current CMS.

**Comment by icaraps** [comment]
> Just some perspective: getting this right is critical to the success of this project. Quick, full-fidelity previews with minimal fuss is a primary motivator for ditching our current CMS.

@iansk I understand. I've worked on the preview GH action to display preview URLs when adoc or book changes are made and submitted as PR in the https://github.com/hlxsites/prisma-cloud-docs repo. 

The output looks like following: 
![image](https://github.com/hlxsites/prisma-cloud-docs-website/assets/6012307/98f5f071-12c9-482e-ab3e-4a3f6fcf8fb7)

The warning is displayed when there is a reference to adoc files in a book that is missing in the repository. 

Navigation should also be working now in preview mode. Next I'm looking into https://github.com/hlxsites/prisma-cloud-docs-website/issues/69. 

Please let me know if you find issues with the GH action to preview content.
