### ISSUE TITLE
Load issue

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#60]
Previously reported here: https://github.com/hlxsites/prisma-cloud-docs-website/issues/42

Sometimes adoc content doesn't load.

Here's a screenshot of what it looks like:

<img width="1472" alt="content-load-issue" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/b9cc62d9-81e5-4784-a0e2-d6890dc04771">

Developer Tools - Console tab

<img width="1472" alt="content-load-issue-dev-tools-console" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/a5325ada-1950-44f0-85f3-cd647e1e82dc">

Developer Tools - Network tab

<img width="1473" alt="content-load-issue-dev-tools-network" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/f89c7a75-2335-4268-b690-b8d14bb622e4">

**Comment by iansk** [comment]
Saw the issue again. Here are screenshots from the console and network tabs from Chrome's developer tools

**Console**

<img width="1471" alt="load-issue2-console" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/ed864bc8-fcb1-4245-afe5-0894484076ed">

**Network tab (screenshot 1/2 scrolled to the top)**

<img width="1505" alt="load-issue2-network1" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/9930fea0-2dbf-4901-a41a-e4ca46c52fb3">

**Network tab (screenshot 2/2, scrolled to the bottom)**

<img width="1512" alt="load-issue2-network2" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/0b60dc8d-b489-4be8-bf7e-1e013bc0b9df">

**Comment by maxakuru** [comment]
@iansk don't suppose you have a way to repro? asking since you managed to get it twice

**Comment by iansk** [comment]
@maxakuru Unfortunately, I haven't found a way to reproduce it yet. When it happens, I click away and back to validate what I'm seeing, and the page loads.

**Comment by iansk** [comment]
Just saw this issue again on this page:

https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/pcee/admin-guide/agentless-scanning/onboard-accounts/onboard-aws

I entered the URL into the address bar, and neither the left nav nor the adoc content loaded. Waited a few minutes. Clicked the refresh button, and it loaded.

**Comment by iansk** [comment]
I can finally reproduce the issue!

Browser: Version 114.0.5735.133 (Official Build) (arm64)

**Repro:**

1. Go to this [link](https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/pcee/admin-guide)

2. Expand the "Welcome" section.

3. Click on the "Getting started" article.

   <img width="342" alt="load-issue-click-article" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/91e58095-511a-4157-a953-7638b60cf1d3">

**Results:**

Everything loads, except the adoc content.

Note that the adoc content loads when you click the browser's reload button.

<img width="1464" alt="load-issue-screen-cap" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/b56e3662-63e0-420d-8e1c-f19a2ad4aac1">

**Expected results**

Everything loads, including the adoc content

**Debug info:**

Screenshots from Chrome's Developer Tools:

<img width="1512" alt="load-issue-dev-tools" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/c7325f44-7d55-4d98-9d5f-87e9e9ccc6b5">

<img width="1501" alt="load-issue-dev-tools-console1" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/1c5d3e90-1804-437b-a159-4f8bf5e01c2d">

<img width="1502" alt="load-issue-dev-tools-console2" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/ca705ea6-f323-455b-a62f-e90ac3d9b2fc">
