### ISSUE TITLE
Left nav - book order - issue still exists

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#63]
Previously reported in https://github.com/hlxsites/prisma-cloud-docs-website/issues/50

Book order still changes in some circumstances. To reproduce:

1. Go to this [page](https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/pcee/admin-guide).

2. In the left nav, scroll to the bottom, until the last book is visible ("Prisma Cloud Intelligence Stream Notifications").

3. Click on "Prisma Cloud Intelligence Stream Notifications"

<img width="344" alt="starting-book-order" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/5d4d0e6e-bae4-420d-b87b-17a33e3e8a41">

**Results:**

Notice that the "Prisma Cloud Intelligence Stream Notifications" book is now second in order.

<img width="345" alt="ending-book-order" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/c019a066-d624-4294-9164-7892cd06b2c6">

**Expected Results**

The "Prisma Cloud Intelligence Stream Notifications" book is still the last book in order.

**Comment by icaraps** [comment]
@maxakuru this seems to be fixed now ?

**Comment by maxakuru** [comment]
I see the issue, I was inserting the "additional lists" always adjacent to the "main book" list
