### ISSUE TITLE
Left nav - missing book

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#64]
The Compute product should have six books in the left nav, but there are only five. The missing book is the Release Notes (or `rn`). The metadata sheet seems to be properly set up, but the book still doesn't appear.

<img width="345" alt="compute-doc-set-five-books" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/a1bc9554-9c53-4390-8b54-e1bc0679b22f">

Note that the "Release Notes" book is versioned. Path to each version in the repo:

* docs/en/compute/30-xx/rn
* docs/en/compute/22-12/rn
* docs/en/compute/22-06/rn
* docs/en/compute/21-08/rn

**Comment by maxakuru** [comment]
@iansk  there's no book for "release notes" for Compute in the `all-books` metadata sheet, there's only 5 for each pcee and 30-xx, where 4 are shared/unversioned

I do see one for cspm, and that seems to be working: https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/cspm/admin-guide

**Comment by iansk** [comment]
@maxakuru Done. I added the "Release Notes" data to the `all-books` tab.

Can I preview my changes without pushing the metadata sheet live?

**Comment by maxakuru** [comment]
looks fixed, closing

**Comment by iansk** [comment]
@maxakuru Re-opening this issue because it's still not fixed. Let me know if you prefer me to open new issues rather than re-open old issues

If you go to this link, you'll see there are still only five books in this "doc set":

https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/pcee/admin-guide

There should be six books. I added the "Release Notes" book to the metadata sheet, as part of the 
`compute` product.

From the Franklin Sidekick, I compared the live vs preview metadata, and they're the same, so I believe you pushed the latest changes live.

Quick question: How can I check the publish status of the metadata sheet from the admin API?

**Comment by iansk** [comment]
There may be something wrong with the formula for `all-books` in column J of the metadata sheet. I added the release notes to the `all-books` tab, but the corresponding entries for related books in `Sheet1` don't contain any reference to the release notes book.

Ex - cell J2 (line breaks added for clarity) - This is the `all-books` entry for the PCEE admin guide in the compute product.

```
/prisma/prisma-cloud/docs/en/compute/pcee/admin-guide;Prisma Cloud Enterprise Edition;;
/prisma/prisma-cloud/docs/en/compute/is-notifications;Prisma Cloud Intelligence Stream Notifications;;
/prisma/prisma-cloud/docs/en/compute/ops-guide;Prisma Cloud Operationalize Guide;;
/prisma/prisma-cloud/docs/en/compute/public-sector;Prisma Cloud Compute Edition Public Sector;;
/prisma/prisma-cloud/docs/en/compute/ref-arch;Prisma Cloud Reference Architecture
```

**Comment by maxakuru** [comment]
@iansk you added release notes for all versions *except* pcee:

![image](https://github.com/hlxsites/prisma-cloud-docs-website/assets/17409558/2c231420-6fe8-4623-b45e-45b0b443d543)

if you add a line with `version -> pcee` it should work
