### ISSUE TITLE
Sitemap isn't updated when a new topic is added to the site

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#71]
When adding a new topic to a book.yml, the sitemap isn't automatically updated to include the new file.

**Repro steps:**

You can review the relevant PR here: https://github.com/hlxsites/prisma-cloud-docs/pull/29

1. Create a new branch in the prisma-cloud-docs repo.

2. Create a new adoc file in one of the book folders.

3. Add the adoc file to the corresponding book.yml file.

4. Commit all changes, push the branch to GitHub.

5. In GitHub, create a PR, then merge the PR into main.

6. Check the sitemap to see if there's a new entry: https://main--prisma-cloud-docs--hlxsites.hlx.live/prisma/prisma-cloud/docs/sitemaps/sitemap-en.xml

**Results:**

No entry in the sitemap file.

**Expected results:**

New entry in the sitemap file.

**Comment by maxakuru** [comment]
sitemap changes are managed using semantic release.. in particular, the worker deploy and sitemap generation/push processes only occurs when a commit message matches a specific pattern

`fix: <comment>` will be the most common pattern for this, for example `fix: update sitemap`, which will bump the worker a patch version, ie. from `x.y.z` to `x.y.(z+1)`

other options are `feat` and `perf` for minor and major version changes, respectively. The [semantic release readme](https://github.com/semantic-release/semantic-release#commit-message-format) has more info.

the reason we don't update on each commit/push is to avoid the relatively expensive process of generating the sitemap even when no changes are made.. 

if having a commit format is too much for authors, it can be managed through using squash commits and setting the commit message on the squash commit before merge; that would put the onus on the person merging, so probably you @iansk

if that's still too much management, we could generate on each commit/push.. I just would have this as the last resort, imo

**Comment by iansk** [comment]
@maxakuru Could we automatically regenerate the sitemap every time there's a push to `main`?

The `semantic-release` approach is cool, but we'll have various people with various technical skill levels managing the repo. Some people will inevitably not recognize PRs that add/delete/rename files and won't correctly add the right commit message to regen sitemaps. To work around it, we'll end up instituting a best practice of adding a generic `fix: xyz` commit message for all squash commits to main. I'd prefer we just short-circuit all of this, and just regen sitemaps on every push to `main`.

What would be the downsides of this approach? Note, we'd probably have a max of 50-60 PRs/week, and more likely 10-25 per week.

**Comment by maxakuru** [comment]
@iansk only downside is performance.. we can try on every commit, it'll probably be fine
