### ISSUE TITLE
[Preview] Can't preview new changes to existing branch

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#72]
If you create a new branch, make changes to it, commit the changes(commit1), and then push the branch to GitHub, you can preview the changes. If you make further changes to the branch, commit them (commit 2), and push the new commit to GitHub, none of the changes from commit2 can be seen in the preview.

This branch has two commits. The branch was pushed to GitHub after creating the first commit.

https://github.com/hlxsites/prisma-cloud-docs/compare/main...ian-ol4

The preview can be seen here. It only shows the state of the branch with the first commit. The second commit isn't shown.

https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/ops-guide/getting-started/test_sitemap?branch=ian-ol4

**Repro**

1. Create a new branch and switch to it.

2. Make a change to a file.

3. Commit the change.

4. Push the new branch to GitHub.

5. Preview the updated file. You can see the change.

6. Make another change to the file.

7. Commit and push the change to GitHub.

8. Preview the updated file. You **can't** see the changes from the latest commit.

**Results**

Only the changes from the first commit can be seen in the preview.

**Expected results**

Every time a commit is pushed to a branch on GitHub, the preview should show the latest state of the branch.

**Comment by icaraps** [comment]
@iansk I can see all changes now. My guess is there is an additional delay when a file is modified again.

@maxakuru If the content is served from https://raw.githubusercontent.com for preview, I suspect that github's raw CDN cache update is not immediate when a file is updated.

**Comment by maxakuru** [comment]
@iansk I also see the updates now, obviously well after the issue was opened.. could you retest and find the duration between commit & change visible? will help us figure out where it's coming from

@icaraps that could definitely be the case, I see a cache hit header that looks an awful lot like github raw is going through fastly. Also github raw has a cache-control TTL of 5 min, it's possible the worker caches the response for that duration. I imagine there's at least some amount of time between commit merge & availability on github raw, even without caching, so we won't ever get to instant..

may be worth making the `fetch` for the article content using `{ cache: 'reload' }` when we're on dev & a branch param is present.. wdyt @icaraps ?

**Comment by maxakuru** [comment]
@iansk pushed a change in #76 .. if you could test again it may be improved

**Comment by icaraps** [comment]
@maxakuru based on https://stackoverflow.com/questions/62785962/get-raw-file-from-github-without-waiting-for-5-minute-cache-update, it looks like you can't bypass the 5mins cache but if you access the document by hash instead of by branch, you're supposed to get the latest version.

**Comment by iansk** [comment]
@maxakuru @icaraps I just tested it now (based on the work merged in https://github.com/hlxsites/prisma-cloud-docs-website/pull/76) - now the page isn't loading at all.

https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/not-applicable/ops-guide/getting-started/getting-started?branch=ian-test-multi-commit-preview

I've been hitting refresh on an incognito tab/window for about 5 minutes. Still nothing.

**Screenshot of non-working page:**

<img width="1463" alt="multi-commit-preview" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/7a381254-85ab-4809-bece-fa7989a2b2b4">

**Comment by iansk** [comment]
More info. When I go to the preview link:

https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/ops-guide/getting-started/test_sitemap?branch=ian-test-multi-commit-preview

I get automatically redirected here:

https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/not-applicable/ops-guide/getting-started/getting-started?branch=ian-test-multi-commit-preview

**Comment by icaraps** [comment]
@iansk You have a typo in the URL it should be: https://main--prisma-cloud-docs-website--hlxsites.hlx.page/prisma/prisma-cloud/en/compute/ops-guide/getting-started/test-sitemap?branch=ian-test-multi-commit-preview

Notice the `test-sitemap` vs `test_sitemap`. In the repo, the folder and file names are using `_` but the translated web paths are using `-` and are lowercased.

**Comment by icaraps** [comment]
@iansk FYI I've started a README for the preview feature. You can find it here https://github.com/hlxsites/prisma-cloud-docs/tree/main/preview#readme
