### ISSUE TITLE
Left nav does not auto expand to active document

### ISSUE THREAD

**Issue by charlieboles** [hlxsites/prisma-cloud-docs-website#74]
**Observation of the Issue/Behavior**
When directly navigating to documentation that is nested at least 3+ levels deep the left nav does not expand correctly. 

**Expected Result/Behavior**
The left nav should expand all parent sections containing the active product documentation

**Steps to Reproduce**
1. Directly navigate to https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/pcee/admin-guide/agentless-scanning/onboard-accounts/onboard-azure
2. Notice that the active documentation is not visible in the left navigation and the user must click  _Onboard Accounts for Agentless Scanning_ to see the active item

Browsers Used
Chrome v114

**Actual Behavior**
<img width="1502" alt="actual" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/2379680/021fd44e-0f9a-42ad-9367-6084ed02ce26">

**Expected Behavior**
<img width="1477" alt="expected" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/2379680/382cb25b-d252-45af-b7aa-626bb387a163">

**Comment by maxakuru** [comment]
closed in #78
