### ISSUE TITLE
Language selector - switching languages doesn't work

### ISSUE THREAD

**Issue by iansk** [hlxsites/prisma-cloud-docs-website#98]
Switching languages using the language selector takes you to a 404 error page.

**Repro:**

1. Go to a [page in the Compute > PCEE Admin Guide.](https://main--prisma-cloud-docs-website--hlxsites.hlx.live/prisma/prisma-cloud/en/compute/pcee/admin-guide/agentless-scanning/onboard-accounts/onboard-aws)

2. From the "Current Language" drop-down, select Japanese.

**Results:**

You get taken to a `404 - Page Not Found` error page.

<img width="1171" alt="localization-lang-selector" src="https://github.com/hlxsites/prisma-cloud-docs-website/assets/6518946/2b138828-c480-4d4d-92b0-ebfb939b77e2">

**Expected results:**

You get taken to the same page in the translated book. If the page doesn't exist in the translated book, you get redirected to the first page of book.

Note that we've only got one placeholder book to test localization. It's for the PCEE Admin Guide for the Compute product. It's located here `docs/jp/compute/pcee/admin-guide`.

**Comment by maxakuru** [comment]
@iansk this is because none of the jp pages are configured in the metadata

**Comment by maxakuru** [comment]
if this is still an issue please reopen with an example
